questions = [
    ("What is the international governing body of soccer?", "FIFA"),
    ("Which country won the first ever World Cup in 1930?", "Uruguay"),
    ("Who is known as 'The King of Clay' in tennis?", "Rafael Nadal"),
    ("How many gold medals did Michael Phelps win at the 2008 Beijing Olympics?", "8"),
    ("What year were the first modern Olympic Games held?", "1896"),
    ("In which sport would you perform a 'Fosbury Flop'?", "High Jump"),
    ("Which country is known as the birthplace of cricket?", "England"),
    ("What is the maximum score possible in 10-pin bowling?", "300"),
    ("Who has won more Grand Slam titles, Serena Williams or Venus Williams?", "Serena Williams"),
    ("Which team has won the most Super Bowls?", "Pittsburgh Steelers"),
    ("In what sport is the Ryder Cup contested?", "Golf"),
    ("Who holds the record for the most points scored in an NBA game?", "Wilt Chamberlain"),
    ("What is the only country to have played in every World Cup?", "Brazil"),
    ("Who was the youngest player to score 10,000 points in the NBA?", "LeBron James"),
    ("What is the diameter of a basketball hoop in inches?", "18"),
    ("In which sport is the Stanley Cup awarded?", "Ice Hockey"),
    ("What sport is known as the 'king of sports'?", "Soccer"),
    ("Who won the FIFA Women's World Cup in 2019?", "United States"),
    ("What is the regulation height for a basketball hoop?", "10 feet"),
    ("In golf, what name is given to a hole score of one under par?", "Birdie"),
    ("Which athlete has won the most Olympic medals?", "Michael Phelps"),
    ("In which country were the first Olympic Games held?", "Greece"),
    ("What number is located opposite 20 on a dartboard?", "5"),
    ("Who is often called the greatest hockey player of all time?", "Wayne Gretzky"),
    ("In which sport would you find a 'scrum'?", "Rugby"),
]